FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git

COPY --from=ghcr.io/astral-sh/uv:0.5.30 /uv /bin/uv

COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY src src
COPY flows/network_speedtest flows/network_speedtest
COPY .git .git

RUN uv sync --extra speedtest