FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git

COPY pyproject.toml pyproject.toml
COPY src src
COPY .git .git

RUN python -m pip install --upgrade pip wheel uv
RUN uv pip install --system .