services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect
      - POSTGRES_DB=prefect
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prefect:
    image: prefecthq/prefect:3-python3.12
    restart: always
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    depends_on:
      - db
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200
      - PREFECT_SERVER_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@db:5432/prefect

volumes:
  postgres_data: {}