services:
  prefect-server:
    # Use a specific version tag in production for stability, e.g., prefecthq/prefect:3.0.0
    image: prefecthq/prefect:3-latest
    command: prefect server start
    environment:
      # Listen on all interfaces within the container.
      PREFECT_SERVER_API_HOST: 0.0.0.0
      # Default Prefect server port inside the container.
      PREFECT_SERVER_API_PORT: 4200
      # PREFECT_UI_URL: Instructs the Prefect server and client (e.g., CLI) how to construct
      # user-facing URLs to the UI. This should be the external URL via the reverse proxy.
      PREFECT_UI_URL: http://localhost/ # Adjust localhost if using a custom domain
      # PREFECT_UI_API_URL: Crucial for reverse proxy setups. Tells the UI (running in the browser)
      # what URL to use for API calls. This must be the external API URL accessible via the proxy.
      PREFECT_UI_API_URL: http://localhost/api/ # Adjust localhost if using a custom domain
      PREFECT_LOGGING_LEVEL: INFO
      # Note: The prefect-server's port (4200) is NOT directly exposed to the host.
      # Access is managed entirely through the Nginx reverse proxy.
    volumes:
      # Persists Prefect server data (SQLite DB, configurations, etc.) across container restarts.
      - prefect_data:/root/.prefect
    networks:
      # Connects to the custom bridge network for inter-service communication.
      - prefect-network

  nginx:
    # Standard Nginx image. Consider pinning to a specific version in production.
    image: nginx:latest
    # Ensures Nginx runs on an amd64 platform, useful for cross-platform consistency (e.g. Apple Silicon hosts).
    platform: linux/amd64 # Optional: remove if not needed or causes issues on your platform
    ports:
      # Exposes Nginx on port 80 of the host machine, making the Prefect UI/API accessible.
      # If using HTTPS, you would typically expose port 443 here as well.
      - "80:80"
    volumes:
      # Mounts the custom nginx.conf into the container, configuring Nginx as a reverse proxy.
      # ':ro' makes the mount read-only within the container for security.
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      # Ensures prefect-server is started before Nginx attempts to proxy to it.
      - prefect-server
    networks:
      # Connects to the same custom bridge network.
      - prefect-network

volumes:
  # Defines the named volume for Prefect server data persistence.
  prefect_data:


networks:
  # Defines a custom bridge network, allowing services to communicate using their service names
  # (e.g., http://prefect-server:4200 from Nginx).
  prefect-network:
